pkg/base/client/kafka.go
=> fix: fix base.client.GetNewReader

cmd/gateway/main.go, gateway/mw/cors.go, gateway/mw/gzip.go, gateway/mw/recovery.go, gateway/mw/sentinel.go
=> style: pack middleware to exclusive package

pkg/kafka/kafka.go
kafka 包内部的某个循环会导致给 readers map 会导致创建比预期多一个的reader并返回错误的ch
=> fix: kafka reader index error

idl/payment.thrift
feat
完善了idl/payment.thrift文件，添加了一些接口
=> feat(payment): update payment interface

Makefile, config/config.example.yaml
fix
将makefile与config中api的错误使用改为了gateway
=> fix: gateway used incorrect service_name

config/sql/commodity.sql, config/sql/payment.sql, config/sql/user.sql
=> fix sql error and revise commodity.sql

config/sql/payment.sql
=> fix: payment.sql

app/gateway/handler/api/user/user_service.go
=> fix: fix user login logic error

app/user/infrastructure/mysql/model.go
=> fix: fix bug in user regitser

app/commodity/domain/service/service.go, app/commodity/usecase/service.go, app/gateway/mw/auth.go, pkg/base/context/context.go, pkg/base/context/login_data.go
流式传输的过程，ctx不能用传统方式传递
由于修改了ctx的存储数据结构，已经和fuu的有差，考虑把序列化移除掉
=> feat: add ctx operation in stream

app/user/usecase/service.go
=> fix: fix bug in user

app/assistant/handler/handler.go, app/assistant/service/login.go, app/assistant/service/login_test.go, app/assistant/service/service.go
fix
assistant的header获取错了(AccessTokenHeader x | AuthHeader √)
=> fix: rename access token context key to auth header

app/order/controllers/rpc/handler.go, app/order/domain/service/service.go, app/order/infrastructure/mysql/db.go, app/order/usecase/service.go, app/order/usecase/usecase.go
=> fix: perfect logic

app/commodity/domain/service/service.go
=> fix: modify delete spu

app/commodity/domain/service/verify.go, app/commodity/usecase/service.go
=> fix: add verify category id

.gitignore, config/alloy/config.alloy, config/prometheus/prometheus.yml, docker/docker-compose.yml
=> feat: prometheus montioring

app/payment/infrastructure/mysql/db_test.go
feat
增加了payment模块的关于db部分的测试，并且测试成功跑通了
=> feat: add test for payment(mysql)

app/commodity/domain/service/init.go, app/commodity/domain/service/service.go, app/commodity/domain/service/verify.go, app/commodity/infrastructure/redis/lock.go, app/commodity/usecase/service.go, app/commodity/usecase/service_test.go, pkg/constants/redis.go
=> feat: add check redis health

Makefile, app/commodity/domain/service/service.go, app/commodity/infrastructure/es/es_test.go, app/commodity/infrastructure/es/es_test_helper.go, app/commodity/infrastructure/mq/mq_test.go, app/commodity/infrastructure/mq/send.go, app/commodity/infrastructure/mysql/db.go, app/commodity/infrastructure/mysql/db_spu_test.go, app/commodity/infrastructure/mysql/db_test_spu_helper.go, app/commodity/infrastructure/redis/redis_test_spu_imgs_helper.go, app/commodity/infrastructure/redis/spu_image_test.go, app/commodity/infrastructure/redis/stock_test.go, app/commodity/infrastructure/redis/stock_test_helper.go
=> feat: add infrastructure test in commodity

app/commodity/domain/service/service.go
=> fix: bugs in update spu

.github/workflows/ci.yaml
=> fix: upgrade ci unbuntu version

app/assistant/cli/server/driver/http/cart_purchase.go
=> fix: fix bugs

.github/workflows/build.yaml
=> build: create build.yaml

.github/workflows/build.yaml
=> fix: add a convert from uppercase to lowercase in build.yaml

Makefile
=> fix: revise remote_repo
